[build]
  # Directory where Netlify should look for your build output (e.g., for React, this is typically 'build')
  publish = "build"
  # Command to build your project (for a React project, this is usually 'npm run build')
  command = "npm run build"

# Redirect all requests to index.html for a single-page application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
